source 'https://rubygems.org'

gem 'prawn'

gem 'minitest'
gem 'rubocop'
gem 'autotest'
gem 'autotest-suffix'
gem 'rubycritic'
gem 'pry'
gem 'pry-doc'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'pry-byebug'
