* Application
** Publish in GitHub
* Calendar
** Print
- Try to print to pdf odd and even
- Try to print only December
* Blog entryf
** Explain calendar design
I'm a systems engineer that writes a lot of code: we have more than 50.000 computers, 1.100 servers and 900 remote offices.
Basically, I manage systems by writing code.

And I'm not very good with my to-do lists: half the time learning, testing and sharing (procrastinating?), the other half absolutely immersed in solving just one problem (sometimes not the most important one).

A few years ago I started to read some articles and books about productivity, delivering on time, lean... and started to practice one of the simplest methods: the pommodoro technique.
It's easy to apply in any environment, and it just works. If you haven't heard about it, take a look at http://www.pommodorotechnique.com

But the pommodoro technique works mainly in the "To Do Today" mode, and I've always liked to work with the whole week view.
On one hand, it gives me context: the work of today is usually related with the previous days.
On the other, you can see how this week is going: done tasks from previous days give you peace, and unfinished ones propell you to work harder or redefine your project schedule.

So, I started to look for something that I could use as a week calendar, and where I could use some pommodorish technique: just to write down the work that needs to be done today, and track the tasks' progress.

You can imagine that I found nothing that I liked. So, I started to think about the week calendar that I would love to use...

The design, was driven by simplicity:
1. Only one font.
2. No graphics, only chars and dots.
3. No colours, just black and only three shades of grey.
4. It could be used with the pommodoro technique.
5. All week view, but with a size as small as possible.
6. Half cm. non invasive grid, that can be used as a ruler
7. All possible space to you (avoid adding unneeded elements).
8. Days on the right, you can write one line up

The result, being a programmer with almost no free time, was a little script written in Ruby, and using the prawn gem that allows you to write PDF documents.

** Add photos
test other dinosaur with milk sharing blindness 

* Blog entry 2
# Why #

I'm a systems engineer that writes a lot of code: we have more than 50.000 computers, 1.100 servers and 900 remote offices.
Basically, I manage systems by writing code.

And I'm not very good with my to-do lists: half the time learning, testing and sharing (procrastinating?), the other half absolutely immersed in solving just one problem (sometimes not the most important one).

So, a few years ago I started to read some articles and books about productivity, delivering on time, lean... and began to practice one of the simplest methods: the pomodoro technique.

It's easy to apply in any environment, and it just works. If you haven't heard about it, take a look at http://www.pomodorotechnique.com

But the pomodoro technique works mainly in the "To Do Today" mode, and I've always liked to work with the whole week picture.
On one hand, it gives me context: the work of today is usually related with the previous days.
On the other, you can see how this week is going: done tasks from previous days give you peace of mind, and unfinished ones propel you to work harder or to redefine your project schedule.

So, I started to look for something that I could use as a week calendar, and where I could use some 'pomodorish' technique: just to write down the work that needs to be done today, and track the tasks' progress.

You can imagine that I found nothing that I liked. So, I started to think about the week calendar that I would love to use...

# How #

The design, was driven by simplicity:
1. Only one font.
2. No graphics, only chars and dots.
3. No colours, just black and only 'three' shades of grey.
4. Easy to use with the pomodoro technique.
5. All week view, but with a size as small as possible.
6. Half cm. non invasive grid, that can be used as a ruler.
7. All possible space to you (avoid adding unneeded elements).
8. Days on the right, you can write one line up.

And being a programmer with almost no free time, I wrote a little script in Ruby, using the prawn gem that allows you to write PDF documents.

# The result #

# How to print the PDF #

As I used a small font size, and different shades of grey to remark the current week, you cannot use any laser printer. Almost all laser printers simulate greys by dithering or halftoning, and small fonts look terrible.

It's better to use a inkjet printer, with any good quality paper. I doesn't need to be photographic paper. I used a cheap inkjet in Black & White mode (medium quality without using colour cartridges) and white A4 120gr/cm paper, and the results were quite good.

If you use an A5 paper, you have the finished product. But if you use another size as I did with my A4 paper, you would need first to arrange two A5 in an A4, and after printing you will need to cut half the A4 to get the calendar. This is not easy: my printer driver was not able to arrange the A5 into a double sided A4, and if you want all the pages with a perfect size, you will have to use a industrial guillotine. I ended by printing manually and then giving the paper to a professional to cut it.

The next time, I probably will send the pdf directly to a professional to do the whole job.

# Bonus #

After writing the code, and having printed the calendar, I started to look for a landscape A5 ring binder... If are still reading you can suppose that I had decided to design and build my own!.

There are lots of tutorials around the internet. So this are only a few tricks, and some pictures that I took during the process.

1. I bought three cheap two-ring binders, and used a Dremel to take the rings apart.
2. The base structure is made of 3mm cardboard. Two rectangles for the covers, and one thin rectangle for the spine. The size has to be at least two cm higher and four wider than an A5, but it depends on your rings and personal preferences.
3. I've used 2mm eva foam and glue to bind the cardboard. Remember to leave about 5mm between the covers and the spine.
4. I've looked for some high quality images of textures on the web (there are zillions), and send them to be printed with an hp latex printer over display panel paper. It resists sun, water and the result was fantastic.

